version: '3'

services:

  app:
    build:
      context: ..
    volumes:
      - './app'
    ports:
      - '3000:3000'
    container_name: ts-express-api-template
    networks:
    - default_network

networks:
  default_network:
    external: true
